name: Draft PR

on:
  push:
    branches-ignore: [main]

permissions:
  contents: read

jobs:
  draft:
    uses: PineappleEmperor/release-flow/.github/workflows/auto-draft-pr.yml@84836b2ab401159f0d41939ef70acff010d10dbf # v1.1.2
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
