name: Lint PR

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions: {}

jobs:
  lint:
    permissions:
      pull-requests: read
    uses: PineappleEmperor/release-flow/.github/workflows/lint-pr.yml@84836b2ab401159f0d41939ef70acff010d10dbf # v1.1.2
