name: Python Validate

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    uses: PineappleEmperor/ha-integration-ci/.github/workflows/python-validate.yml@7aae20dcc8854e14197dd259d15f6368d1478eba # v1.0.4
