name: Python Validate

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    uses: PineappleEmperor/ha-integration-ci/.github/workflows/python-validate.yml@7d06f064d77f169910322997cbab910195661f73 # v1.0.1
