name: Create Release ZIP

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    uses: PineappleEmperor/ha-integration-ci/.github/workflows/release.yml@6ead6b439af8c4399e767f82d9778b4aa2154885 # v2.0.0
