name: Create Release ZIP

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    uses: PineappleEmperor/ha-integration-ci/.github/workflows/release.yml@7aae20dcc8854e14197dd259d15f6368d1478eba # v1.0.4
