name: Create Release ZIP

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    uses: PineappleEmperor/ha-integration-ci/.github/workflows/release.yml@2b858891d911d7d06f2c33540c41dc47a515ed9c # v2.0.0
